alias ga="git add"
alias gb="git branch"
alias gc="git checkout"
alias gco="git commit"
alias gd="git diff"
alias gl="git log"
alias glg="git log --graph --oneline"
alias gs="git status"

alias cd..="cd .."
alias gerp="grep"
alias vi="vim"
alias vim="nvim"
alias sl="ls"

alias dfloki="floki -c $HOME/workspace/floki.yaml"
